# Diamond trigonometry
April 11, 2024

I need math that lets me input "steps over" and "steps back" from a base or other anchor, and it adjusts the coordinates on a diamond rotated 45 degrees.  

In [5]:
import numpy as np

In [1]:
old_pos = (1130, 1055)

target_pos = (1145, 951)

## Let's just test dive numpy

In [10]:
adjust = np.array([ [6.4, 6.4], [8.5, 8.5]])

steps_posNeg = np.array([ [-1, -1], [1, -1] ])

In [11]:
all_xy = adjust * steps_posNeg
all_xy

array([[-6.4, -6.4],
       [ 8.5, -8.5]])

In [12]:
x = np.sum(all_xy[:, 0])
y = np.sum(all_xy[:, 1])
adjust = np.array([x, y])
adjust

array([  2.1, -14.9])

In [13]:
adjust * 6.99

array([  14.679, -104.151])

## Okay, let's do this

In [5]:
steps = (9, 12) # over_back

steps_posNeg = np.array([ [-1, -1], [1, -1] ]) ## second tuple says x moves rightward, y moves up

pixels_per_step = 7

In [20]:
steps_posNeg

array([[-1, -1],
       [ 1, -1]])

In [16]:
# Get the a sides of the 'over' triangle

over_a = np.sqrt( (steps[0] **2)/2 ) 
over_a

6.363961030678928

In [17]:
back_a = np.sqrt( (steps[1] **2)/2 ) 
back_a 

8.48528137423857

## Now as a function

In [14]:
def steps_to_pos(old_pos, steps, steps_posNeg):
    over_a = np.sqrt( (steps[0] **2)/2 )
    back_a = np.sqrt( (steps[1] **2)/2 )
    
    adjust = np.array([ [over_a, over_a], [back_a, back_a]])
    
    all_xy = adjust * steps_posNeg
    
    #sum x's and y's
    x = np.sum(all_xy[:, 0])
    y = np.sum(all_xy[:, 1])
    
    adjust = np.array( [x, y]) * pixels_per_step
    
    return old_pos + adjust    

In [15]:
steps_to_pos(old_pos, steps, steps_posNeg)

array([1144.8492424 ,  951.05530317])

In [17]:
target_pos

(1145, 951)

## Testing my visual studio code

In [1]:
steps_adjust = {    "f3": [(9, 12), [(-1, -1), (1, -1)] ],
                    "f4": [(-5, 12), [(1,1), (1,-1)]  ],
                    "f5": [ (7, 12), [(1,-1), (-1, -1)]  ],
                    "f6": [ (-7, 15), [(-1, 1), (-1, -1)]  ], 
                }

In [6]:
np.array(steps_adjust['f3'][1])

array([[-1, -1],
       [ 1, -1]])